### ISSUE TITLE
`behat.yml` file missing after package scaffolding 

### ISSUE THREAD

**Issue by ernilambar** [wp-cli/scaffold-package-command#235]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

Error: `behat.yml` file missing after I run `composer run behat`.

**Describe how other contributors can replicate this bug**

- `wp scaffold package rabmalin/testing --dir=~/Temp/testing`
- `composer install`
- `composer run behat`

Error:

```
Did not detect "behat.yml" file, skipping Behat tests.
```
After I add this file with following content, test run properly.

```
default:
  suites:
    default:
      contexts:
        - WP_CLI\Tests\Context\FeatureContext
      paths:
        - features

```
